version: '3.4'

networks:
  KipaNet:

services:
  db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
        - KipaNet


  kipa-plus:
    image: ${DOCKER_REGISTRY-}kipaplus
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - db
    networks:
        - KipaNet

   
        