version: '3.4'

networks:
  KipaNet:

volumes:
  UploadFiles:
  DataBaseFiles:

services:
  db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
        - KipaNet
    volumes:
        - type: volume
          source: DataBaseFiles
          target: /var/opt/mssql

  kipa-plus:
    image: ${DOCKER_REGISTRY-}kipaplus
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - db
    networks:
        - KipaNet
    environment:
      TZ: "Europe/Helsinki"
    volumes:
        - type: volume
          source: UploadFiles
          target: /UploadedFiles

   
        