version: '3.4'

networks:
  KisaKuikkaNetwork:

volumes:
  UploadFiles:
  DataBaseFiles:

services:
  db:
    container_name: KisaKuikka-DB
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
        - KisaKuikkaNetwork
    volumes:
        - type: volume
          source: DataBaseFiles
          target: /var/opt/mssql

  Kisa-Kuikka:
    container_name: Kisa-Kuikka
    image: arttukuikka/kipa-plus:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - db
    ports:
        - 8001:80
    networks:
        - KisaKuikkaNetwork
    environment:
      TZ: "Europe/Helsinki"
      DB_HOST: "db"
      DB_PORT: "1433"
      DB_NAME: "KisaKuikka"
      DB_USER: "sa"
      DB_USER_PASSWORD: "S3cur3P@ssW0rd!"
      DefaultAdminUser: "admin@arttukuikka.fi"
      FONTAWESOME_KIT_URL: "https://kit.fontawesome.com/b0da54152e.js"
    volumes:
        - type: volume
          source: UploadFiles
          target: /UploadedFiles

   
        
