version: '3.4'

networks:
  KipaNet:

volumes:
  UploadFiles:
  DataBaseFiles:

services:
  db:
    container_name: Kipa-DB
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
        - KipaNet
    volumes:
        - type: volume
          source: DataBaseFiles
          target: /var/opt/mssql

  kipa-plus:
    container_name: Kipa-Plus
    image: arttukuikka/kipaplus:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - db
    ports:
        - 8001:80
    networks:
        - KipaNet
    environment:
      TZ: "Europe/Helsinki"
      DB_HOST: "db"
      DB_PORT: "1433"
      DB_NAME: "KipaPlus"
      DB_USER: "sa"
      DB_USER_PASSWORD: "S3cur3P@ssW0rd!"
    volumes:
        - type: volume
          source: UploadFiles
          target: /UploadedFiles

   
        
