name: Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build latest"]
    types:
      - completed

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
      - name: Pysäytä container
        continue-on-error: true
        run: docker kill Kisa-Kuikka

      - name: Poista container
        continue-on-error: true
        run: docker container rm Kisa-Kuikka

      - name: Poista vanha image
        continue-on-error: true
        run: docker image rm arttukuikka/kisakuikka
        
      - name: lataa uusi
        run: docker pull arttukuikka/kisakuikka:latest
        
        
      - name: suorita compose
        working-directory: /home/administrator/KisaKuikka
        run: docker compose up -d
