name: 'Build latest'

on:
  push:
    branches:
    - Production

jobs:
  build-and-publish-package:
    name: 'Build Package'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Build image
        run: docker compose build 
        
      - name: Docker Push
        run: Docker push ${{secrets.DOCKER_USER}}/kipaplus
        
