name: 'Build latest'

on:
  push:
    branches:
    - production

jobs:
  build-and-publish-latest:
    name: 'Build Package'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: arttukuikka/kipa-plus
          tags: latest
          platforms: linux/amd64,linux/arm64
